alias ..='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'
alias .7='cd ../../../../../../..'

alias l='ls -lAh'
alias lsn='ls -lAh; echo "------------"; ls -A | wc -l'
alias his='history'
alias sd='shutdown now'
alias sr='shutdown -r now'
alias daze='date +"year: %Y, month: %m, day: %d, hours: %H, minutes: %M" | tee /dev/tty | tr -d "\n" | clip.exe'
